version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: pki_buuns
      POSTGRES_USER: pki_user
      POSTGRES_PASSWORD: secure_password
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  api:
    build: .
    depends_on:
      - db
      - redis
    ports:
      - "8001:8001"
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql+asyncpg://pki_user:secure_password@db:5432/pki_buuns
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 0
      LOG_LEVEL: INFO
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8001"]

volumes:
  db-data:

